#!/bin/sh

cleanup() {
    for tmpfile in $temp_files; do
        [ -f "$tmpfile" ] && rm -f "$tmpfile"
    done
}
trap cleanup EXIT

mktemp_tracked() {
    tmp="$(mktemp "$@")"
    temp_files="$temp_files $tmp"
    echo "$tmp"
}

fontdl() {
    local fontdir="$(fontdir "$1-$2")"
    if [ ! -d "$fontdir" ]; then
        output="$(mktemp_tracked).tmp"
        curl --progress-bar -L --output "$output" "$3"
        oldfiles="$(ls -d "$(fontdir)/$1-"* 2>/dev/null)"
        mkdir -p "$fontdir"
        unzip -d "$fontdir" "$output"
        [ -n "$oldfiles" ] && rm -rf "$oldfiles"
    fi
}

jb_dir="$(fontdir "jetbrainsmono-2.304")"
if [ ! -d "$jb_dir" ]; then
    output="$(mktemp_tracked).tmp"
    curl --progress-bar -L --output "$output" "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip"
    oldfiles="$(ls -d "$(fontdir)"/jetbrains* 2>/dev/null)"
    mkdir -p "$jb_dir"
    unzip -d "$jb_dir" "$output" fonts/ttf/JetBrainsMonoNL-Regular.ttf fonts/ttf/JetBrainsMono-Regular.ttf
    [ -n "$oldfiles" ] && rm -rf "$oldfiles"
fi

fontdl "maplemonoNF" "7.9" "https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-NF-unhinted.zip"
fontdl "maplemono" "7.9" "https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-TTF.zip"
fontdl "nf-symbols" "3.5.1" "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.1/NerdFontsSymbolsOnly.zip"

if [ "linux" = "$ostype" ]; then
    fc-cache -f
fi
